# 公共配置文件
server:
  port: 8080
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

spring:
  application:
    name: FollowYourHeart
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  jackson:
    # 设置时区
    time-zone: GMT+8
    # 设置返回格式
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    # 自动转换下划线到驼峰
    map-underscore-to-camel-case: true
    # 将使用标准输出流（stdout）来打印日志信息
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）


# springdoc-openapi 项目配置
springdoc:
  # 默认是 false，需要设置为 true
  # 针对参数解析 ParameterObject 的问题说明
  default-flat-param-object: true
  api-docs:
    enabled: ${knife4j.enable}
    path: /v3/api-docs
  swagger-ui:
    enabled: ${knife4j.enable}
    path: /swagger-ui/index.html
    tags-sorter: alpha
    operations-sorter: alpha
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.fyh.controller

# knife4j 的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn